version: "0.1.4"

display:
    command_line: "user@chatimus ~$ "
    address: ""

# MUST include the socket addresses
# used by your services. So if your twitch socket address is
# `tcp://127.0.0.1:5555`, then you need to put that in the list below.
sockets_to_connect_to: 
    [
        '',
    ]

services:

    irc:
        twitch:
            display_missing: true

    xmpp:
        livecoding:
            display_missing: true

    socket_io:
        watchpeoplecode:
            display_missing: true

    youtube:
        display_missing: true
