# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VCenterMonitor.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

from ServerSettingsUI import Ui_ServerSettingDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 607)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/Activity Monitor (1).png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.MainTap = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTap.setTabPosition(QtWidgets.QTabWidget.North)
        self.MainTap.setObjectName("MainTap")
        self.tabConnection = QtWidgets.QWidget()
        self.tabConnection.setObjectName("tabConnection")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabConnection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetCom = QtWidgets.QWidget(self.tabConnection)
        self.widgetCom.setObjectName("widgetCom")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widgetCom)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnServerStart = QtWidgets.QPushButton(self.widgetCom)
        self.btnServerStart.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            ":/icon/icon/turn_on_off_power-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnServerStart.setIcon(icon1)
        self.btnServerStart.setObjectName("btnServerStart")
        self.horizontalLayout.addWidget(self.btnServerStart)
        self.btnServerStop = QtWidgets.QPushButton(self.widgetCom)
        self.btnServerStop.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(
            ":/icon/icon/turn_off_on_power-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnServerStop.setIcon(icon2)
        self.btnServerStop.setObjectName("btnServerStop")
        self.horizontalLayout.addWidget(self.btnServerStop)
        self.btnSetting = QtWidgets.QPushButton(self.widgetCom)
        self.btnSetting.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/seo2-18-32.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSetting.setIcon(icon3)
        self.btnSetting.setObjectName("btnSetting")
        self.horizontalLayout.addWidget(self.btnSetting)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.grvClients = QtWidgets.QListView(self.widgetCom)
        self.grvClients.setObjectName("grvClients")
        self.gridLayout_3.addWidget(self.grvClients, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.widgetCom)
        self.MainTap.addTab(self.tabConnection, "")
        self.tabCOM = QtWidgets.QWidget()
        self.tabCOM.setObjectName("tabCOM")
        self.gridLayout = QtWidgets.QGridLayout(self.tabCOM)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbbConnections = QtWidgets.QComboBox(self.tabCOM)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.cbbConnections.sizePolicy().hasHeightForWidth())
        self.cbbConnections.setSizePolicy(sizePolicy)
        self.cbbConnections.setObjectName("cbbConnections")
        self.verticalLayout_2.addWidget(self.cbbConnections)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txtMessage = QtWidgets.QLineEdit(self.tabCOM)
        self.txtMessage.setObjectName("txtMessage")
        self.horizontalLayout_4.addWidget(self.txtMessage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnSendMessage = QtWidgets.QPushButton(self.tabCOM)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btnSendMessage.sizePolicy().hasHeightForWidth())
        self.btnSendMessage.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/17-48.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSendMessage.setIcon(icon4)
        self.btnSendMessage.setAutoDefault(False)
        self.btnSendMessage.setDefault(False)
        self.btnSendMessage.setFlat(False)
        self.btnSendMessage.setObjectName("btnSendMessage")
        self.horizontalLayout_6.addWidget(self.btnSendMessage)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.txtOutput = QtWidgets.QTextEdit(self.tabCOM)
        self.txtOutput.setObjectName("txtOutput")
        self.horizontalLayout_5.addWidget(self.txtOutput)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.MainTap.addTab(self.tabCOM, "")
        self.tapEvent = QtWidgets.QWidget()
        self.tapEvent.setObjectName("tapEvent")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tapEvent)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.tapEvent)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.txtRuntime = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.txtRuntime.setObjectName("txtRuntime")
        self.verticalLayout_4.addWidget(self.txtRuntime)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtFromDate = QtWidgets.QDateTimeEdit(self.layoutWidget1)
        self.txtFromDate.setObjectName("txtFromDate")
        self.horizontalLayout_2.addWidget(self.txtFromDate)
        self.txtToDate = QtWidgets.QDateTimeEdit(self.layoutWidget1)
        self.txtToDate.setObjectName("txtToDate")
        self.horizontalLayout_2.addWidget(self.txtToDate)
        self.btnSearchLog = QtWidgets.QPushButton(self.layoutWidget1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/Search-48.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSearchLog.setIcon(icon5)
        self.btnSearchLog.setObjectName("btnSearchLog")
        self.horizontalLayout_2.addWidget(self.btnSearchLog)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.grvEvents = QtWidgets.QListView(self.layoutWidget1)
        self.grvEvents.setObjectName("grvEvents")
        self.verticalLayout_5.addWidget(self.grvEvents)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.MainTap.addTab(self.tapEvent, "")
        self.horizontalLayout_3.addWidget(self.MainTap)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/logout-16.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon6)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionStart = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(
            ":/icon/icon/turn_on_off_power-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon7)
        self.actionStart.setShortcut("")
        self.actionStart.setObjectName("actionStart")
        self.actionStop_Server = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(
            ":/icon/icon/turn_off_on_power-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop_Server.setIcon(icon8)
        self.actionStop_Server.setObjectName("actionStop_Server")
        self.menuFile.addAction(self.actionStart)
        self.menuFile.addAction(self.actionStop_Server)
        self.menuFile.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.MainTap.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.setupEvent(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VCenter Monitor"))
        self.btnServerStart.setText(_translate("MainWindow", "Start"))
        self.btnServerStop.setText(_translate("MainWindow", "Stop"))
        self.btnSetting.setText(_translate("MainWindow", "Settings"))
        self.MainTap.setTabText(self.MainTap.indexOf(
            self.tabConnection), _translate("MainWindow", "Server/Client"))
        self.btnSendMessage.setText(_translate("MainWindow", "Send"))
        self.MainTap.setTabText(self.MainTap.indexOf(
            self.tabCOM), _translate("MainWindow", "COM"))
        self.label.setText(_translate("MainWindow", "Run time"))
        self.btnSearchLog.setText(_translate("MainWindow", "Search"))
        self.MainTap.setTabText(self.MainTap.indexOf(
            self.tapEvent), _translate("MainWindow", "Event logs"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionQuit.setText(_translate("MainWindow", "Exit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStop_Server.setText(_translate("MainWindow", "Stop"))
        self.actionStop_Server.setShortcut(
            _translate("MainWindow", "Ctrl+Alt+T"))

    def setupEvent(self, MainWindow):
        self.btnSetting.clicked.connect(self.openServerSettingsDialog)

    def openServerSettingsDialog(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_ServerSettingDialog()
        self.ui.setupUi(self.window)
        self.window.show()


import resource_rc

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
