version: '3'

services:
  webapi:
    image: webapi
    container_name: maptemplate.api
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5000:80"
    networks:
      mapnet:
        ipv4_address: 10.0.0.10

networks:
    mapnet:
        external:
          name: mapnet