version: '3'

networks:
  mapnet:
    external:
      name: mapnet

services:
  webapi:
    image: webapi
    container_name: maptemplate.api
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    expose:
      - "5000"
    networks:
      mapnet:
        ipv4_address: 10.0.0.10

  proxy:
    image: proxy
    container_name: maptemplate.nginx-proxy
    build:
      context: ./Proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - webapi
    networks:
      - mapnet
        